languageCode = 'en-us'
baseURL = "https://ret2school.github.io"
title = "ret2school"
theme = "m10c"
themesDir = "themes/"
paginate = 12

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/post/list_team/"

[params]
  avatar = "pic.jpeg"
  author = "nasm"
  description = "Just a bunch of french ctf players"
[markup]
  [markup.highlight]
    style = "dracula"
    tabWidth = 4
